name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main, auth]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        if: success()
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORK_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: ZKFKSXK
          destination-repository-name: kallong
          user-email: ${{ secrets.FORK_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: ${{ github.ref_name }}
      - name: Test get variable exported by push-to-another-repository
        if: success()
        run: echo $DESTINATION_CLONED_DIRECTORY
      - name: Notify build failure
        if: failure()
        run: echo "Build failed! Push to another repository skipped."
